# REQUIRED: specify the name of the folders mapped to each file type
[file_types]
Notes = [".md", ".rtf", ".txt"]
Docs = [".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx"]
EXE = [".exe", ".appimage", ".msi"]
Vids = [".mp4", ".mov", ".avi", ".mkv"]
Compressed = [".zip", ".rar", ".tar", ".gz", ".7z"]
Scripts = [".sh", ".bat"]
Installers = [".deb", ".rpm"]
Books = [".epub", ".mobi"]
Music = [".mp3", ".wav", ".ogg", ".flac"]
PDFS = [".pdf"]
Pics = [".bmp", ".gif", ".jpg", ".jpeg", ".svg", ".png"]
Torrents = [".torrent"]
CODE = [
    ".c",
    ".h",
    ".py",
    ".rs",
    ".go",
    ".js",
    ".ts",
    ".jsx",
    ".tsx",
    ".html",
    ".css",
    ".php",
    ".java",
    ".cpp",
    ".cs",
    ".vb",
    ".sql",
    ".pl",
    ".swift",
    ".kt",
    ".r",
    ".m",
    ".asm",
]
Markup = [
    ".json",
    ".xml",
    ".yml",
    ".yaml",
    ".ini",
    ".toml",
    ".cfg",
    ".conf",
    ".log",
]

# OPTIONAL: debug level for stdout logging. if not specified, defaults to "off"
[debug]
level = "info" # "info", "debug", "warn", "error", "trace", "off"
